In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None) # Show all columns when displaying DataFrames

In [24]:
df = pd.read_csv(r"D:\Personal\Data Science\Data Science\End to End Project\Datasets\archive\Airbnb_Open_Data.csv")

In [4]:
df.head(10)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN
6,1004650,BlissArtsSpace!,61300605564,NaN,Alberta,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2015.0,$71,$14,45.0,49.0,10/5/2017,0.40,5.0,1.0,224.0,Please no shoes in the house so bring slippers...,NaN
7,1005202,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0,10/5/2017,0.40,5.0,1.0,219.0,House Guidelines for our BnB We are delighted ...,NaN
8,1005754,Large Furnished Room Near B'way,79384379533,verified,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,US,True,strict,Private room,2005.0,"$1,018",$204,2.0,430.0,6/24/2019,3.47,3.0,1.0,180.0,- Please clean up after yourself when using th...,NaN
9,1006307,Cozy Clean Guest Room - Family Apt,75527839483,unconfirmed,Carl,Manhattan,Upper West Side,40.80178,-73.96723,United States,US,False,strict,Private room,2015.0,$291,$58,2.0,118.0,7/21/2017,0.99,5.0,1.0,375.0,NO SMOKING OR PETS ANYWHERE ON THE PROPERTY 1....,NaN

In [6]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [8]:
df.shape

(102599, 26)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

In [5]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [ ]:
# columns that we will keep for our analysis 
''' Method 1 here we directlt create a dataframe with the columns we want to keep and drop the rest.
columns_to_keep = df[[ 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review']]

columns_to_drop = df[[col for col in df.columns if col not in columns_to_keep]] '''

In [25]:
columns_to_keep = [ 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review']

columns_to_drop = [col for col in df.columns if col not in columns_to_keep]

In [27]:
print(len(columns_to_keep))
print(len(columns_to_drop))

19
7

In [40]:
# now filter the dataframe to keep only the columns we want to keep and drop the rest.
df = df[columns_to_keep]

In [41]:
df.shape

(102599, 19)

In [44]:
df.rename(columns = {"NAME": "name", "Construction year": "construction_year"} , inplace = True)

df.columns

Index(['name', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'construction_year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review'],
      dtype='object')

In [47]:
# if you want to change the entire column header to title case you can do it like this.

df.columns = df.columns.str.title()

In [50]:
# method 2 

for col in df.columns:
    df.rename(columns = {col: col.title().replace(" ", "_")}, inplace = True)

In [51]:
df.columns

Index(['Name', 'Host_Id', 'Host_Identity_Verified', 'Host_Name',
       'Neighbourhood_Group', 'Neighbourhood', 'Lat', 'Long', 'Country',
       'Country_Code', 'Instant_Bookable', 'Cancellation_Policy', 'Room_Type',
       'Construction_Year', 'Price', 'Service_Fee', 'Minimum_Nights',
       'Number_Of_Reviews', 'Last_Review'],
      dtype='object')

In [52]:
# method 3 using empty list and for loop

new_columns = []

for col in df.columns:
    new_col = col.title().replace(" ", "_")
    new_columns.append(new_col)

In [54]:
df_new = df.copy() # we create a copy of the original dataframe to avoid modifying it directly
df_new.columns = new_columns # we assign the new column names to the copy of the dataframe
df_new.columns

Index(['Name', 'Host_Id', 'Host_Identity_Verified', 'Host_Name',
       'Neighbourhood_Group', 'Neighbourhood', 'Lat', 'Long', 'Country',
       'Country_Code', 'Instant_Bookable', 'Cancellation_Policy', 'Room_Type',
       'Construction_Year', 'Price', 'Service_Fee', 'Minimum_Nights',
       'Number_Of_Reviews', 'Last_Review'],
      dtype='object')

In [55]:
df.duplicated().sum()

np.int64(541)

In [ ]:
df[df.duplicated(keep= 'first')] # what keep = false does is it shows all the duplicated rows instead of just one of them.
# keep = first shows all the duplicated rows except the first occurrence of the duplicate, so first occurence will be considered as unique and the rest will be considered as duplicates. 
# yaane first row is false and the rest of the duplicates will be true.
# while keep = last shows all the duplicated rows except the last occurrence of the duplicate. all the duplicates will be true except the last one which will be false.
# keep = false shows all the duplicated rows including the first and last occurrence of the duplicate. all the duplicates will be true. so it will show all the duplicated rows.

,Name,Host_Id,Host_Identity_Verified,Host_Name,Neighbourhood_Group,Neighbourhood,Lat,Long,Country,Country_Code,Instant_Bookable,Cancellation_Policy,Room_Type,Construction_Year,Price,Service_Fee,Minimum_Nights,Number_Of_Reviews,Last_Review
102058,Master Bedroom with private Bathroom & Balcony,55110690425,unconfirmed,UZeyir,Queens,Maspeth,40.74056,-73.90635,United States,US,True,strict,Private room,2016.0,$706,$141,1.0,1.0,11/14/2021
102059,Cozy 2 br in sunny Fort Greene apt,80193772189,verified,Sally,Brooklyn,Fort Greene,40.68701,-73.97555,United States,US,False,flexible,Private room,2020.0,$651,$130,3.0,38.0,11/13/2021
102060,Duplex w/ Terrace @ Box House Hotel,72991962259,verified,The Box House Hotel,Brooklyn,Greenpoint,40.73756,-73.95350,United States,US,False,strict,Hotel room,2016.0,$907,$181,3.0,10.0,11/13/2021
102061,"Cozy, clean Greenpoint room with yard access",74975156081,verified,Dawn,Brooklyn,Greenpoint,40.72516,-73.95004,United States,US,False,strict,Private room,2013.0,$589,$118,30.0,38.0,11/13/2021
102062,2BR XL Loft: Cleaning CDC guidelines implemented,85844415221,unconfirmed,Vida,Brooklyn,Greenpoint,40.72732,-73.94185,United States,US,False,flexible,Entire home/apt,2015.0,$356,$71,30.0,13.0,11/13/2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN

In [ ]:
df[df.duplicated(keep=False)].sort_values(by=df.columns.tolist()) # this will show us the duplicated rows sorted by all the columns in the dataframe.

,Name,Host_Id,Host_Identity_Verified,Host_Name,Neighbourhood_Group,Neighbourhood,Lat,Long,Country,Country_Code,Instant_Bookable,Cancellation_Policy,Room_Type,Construction_Year,Price,Service_Fee,Minimum_Nights,Number_Of_Reviews,Last_Review
35134,"""In the Clouds"" Brooklyn Heights Studio",7007990163,verified,Jenna,Brooklyn,Brooklyn Heights,40.695030,-73.994750,United States,US,False,moderate,Entire home/apt,2012.0,$306,$61,8.0,1.0,9/27/2018
102464,"""In the Clouds"" Brooklyn Heights Studio",7007990163,verified,Jenna,Brooklyn,Brooklyn Heights,40.695030,-73.994750,United States,US,False,moderate,Entire home/apt,2012.0,$306,$61,8.0,1.0,9/27/2018
62531,# 2 One Lexury Bedroom close to JFK AIRPORT,12648350548,verified,Gelen,Queens,Springfield Gardens,40.664089,-73.754173,United States,US,True,moderate,Private room,2009.0,$943,$189,3.0,9.0,11/10/2021
102113,# 2 One Lexury Bedroom close to JFK AIRPORT,12648350548,verified,Gelen,Queens,Springfield Gardens,40.664089,-73.754173,United States,US,True,moderate,Private room,2009.0,$943,$189,3.0,9.0,11/10/2021
62639,#510 Furnished studio in the heart of Manhattan,22417870465,verified,Best Inns USA,Manhattan,Gramercy,40.733810,-73.985120,United States,US,False,flexible,Entire home/apt,2016.0,$641,$128,30.0,1.0,11/6/2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102328,☆ Manhattan's Retreat - Blocks from Times Square!,46042736282,verified,Louis,Manhattan,Hell's Kitchen,40.756550,-73.995350,United States,US,True,strict,Private room,2020.0,$793,$159,1.0,44.0,7/4/2019
34995,☆ Secret Hideaway - Blocks from Times Square!,81558036123,verified,Louis,Manhattan,Hell's Kitchen,40.756580,-73.995680,United States,US,False,flexible,Private room,2016.0,$63,$13,1.0,41.0,6/18/2019
102325,☆ Secret Hideaway - Blocks from Times Square!,81558036123,verified,Louis,Manhattan,Hell's Kitchen,40.756580,-73.995680,United States,US,False,flexible,Private room,2016.0,$63,$13,1.0,41.0,6/18/2019
9168,♡Private Rm/Women's Safe Art Home♡,27646270360,unconfirmed,Sarah,Brooklyn,Bedford-Stuyvesant,40.684110,-73.932080,United States,US,False,flexible,Private room,2021.0,$618,$124,1.0,4.0,10/7/2015
102544,♡Private Rm/Women's Safe Art Home♡,27646270360,unconfirmed,Sarah,Brooklyn,Bedford-Stuyvesant,40.684110,-73.932080,United States,US,False,flexible,Private room,2021.0,$618,$124,1.0,4.0,10/7/2015

In [ ]:
# now we want to remove the duplicate and keep only one of the duplicates, we can use the drop_duplicates() method.

df.drop_duplicates(inplace=True) # so this rows will drop all the duplicate rows and keep only one of the duplicates. 
# in this case it will keep the first occurrence of the duplicate and drop the rest. and the duplicate is  when all the columns are similar to the other row.

In [69]:
df.shape

(102058, 19)

In [72]:
df.describe()

,Host_Id,Lat,Long,Construction_Year,Minimum_Nights,Number_Of_Reviews
count,1.020580e+05,102050.000000,102050.000000,101844.000000,101658.000000,101875.000000
mean,4.926738e+10,40.728097,-73.949652,2012.488090,8.126640,27.517948
std,2.853742e+10,0.055852,0.049502,5.765838,30.616698,49.571744
min,1.236005e+08,40.499790,-74.249840,2003.000000,-1223.000000,0.000000
25%,2.459924e+10,40.688730,-73.982580,2007.000000,2.000000,1.000000
50%,4.912865e+10,40.722290,-73.954440,2012.000000,3.000000,7.000000
75%,7.400619e+10,40.762760,-73.932350,2017.000000,5.000000,31.000000
max,9.876313e+10,40.916970,-73.705220,2022.000000,5645.000000,1024.000000

In [74]:
df.describe(include='object').T

                         count unique                  top    freq
Name                    101808  61281  Home away from home      33
Host_Identity_Verified  101769      2          unconfirmed   50944
Host_Name               101654  13190              Michael     878
Neighbourhood_Group     102029      7            Manhattan   43557
Neighbourhood           102042    224   Bedford-Stuyvesant    7898
Country                 101526      1        United States  101526
Country_Code            101927      1                   US  101927
Instant_Bookable        101953      2                False   51186
Cancellation_Policy     101982      3             moderate   34162
Room_Type               102058      4      Entire home/apt   53429
Price                   101811   1151                $206      135
Service_Fee             101785    231                $216      523
Last_Review              86226   2477            6/23/2019    2436

In [75]:
df.isnull().sum()

Name                        250
Host_Id                       0
Host_Identity_Verified      289
Host_Name                   404
Neighbourhood_Group          29
Neighbourhood                16
Lat                           8
Long                          8
Country                     532
Country_Code                131
Instant_Bookable            105
Cancellation_Policy          76
Room_Type                     0
Construction_Year           214
Price                       247
Service_Fee                 273
Minimum_Nights              400
Number_Of_Reviews           183
Last_Review               15832
dtype: int64

In [82]:
df.isnull().mean() * 100# this will give us the percentage of missing values in each column. we can also use .round(2) to round the percentage to 2 decimal places.

Name                       0.244959
Host_Id                    0.000000
Host_Identity_Verified     0.283172
Host_Name                  0.395853
Neighbourhood_Group        0.028415
Neighbourhood              0.015677
Lat                        0.007839
Long                       0.007839
Country                    0.521272
Country_Code               0.128358
Instant_Bookable           0.102883
Cancellation_Policy        0.074467
Room_Type                  0.000000
Construction_Year          0.209685
Price                      0.242019
Service_Fee                0.267495
Minimum_Nights             0.391934
Number_Of_Reviews          0.179310
Last_Review               15.512748
dtype: float64

In [83]:
df[df['Name'].isna()]

,Name,Host_Id,Host_Identity_Verified,Host_Name,Neighbourhood_Group,Neighbourhood,Lat,Long,Country,Country_Code,Instant_Bookable,Cancellation_Policy,Room_Type,Construction_Year,Price,Service_Fee,Minimum_Nights,Number_Of_Reviews,Last_Review
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
57,NaN,18424415847,unconfirmed,Carina,Manhattan,Lower East Side,40.72004,-73.99104,United States,US,True,flexible,Private room,2009.0,"$1,024",$205,5.0,19.0,5/18/2019
58,NaN,48877238684,NaN,Sophia,Manhattan,Hell's Kitchen,40.75531,-73.99293,United States,US,True,strict,Private room,2006.0,$658,$132,2.0,289.0,6/9/2019
59,NaN,71987706184,verified,Rosie,Brooklyn,Greenpoint,40.72401,-73.93788,United States,US,False,flexible,Private room,2020.0,$543,$109,4.0,138.0,6/4/2019
60,NaN,85649449746,verified,Frederick,Manhattan,SoHo,40.72210,-73.99775,United States,US,True,strict,Entire home/apt,2019.0,$256,$51,30.0,21.0,6/29/2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100074,NaN,19395911932,unconfirmed,Alex,Queens,Astoria,40.75989,-73.91343,United States,US,True,strict,Entire home/apt,2006.0,$752,$150,21.0,6.0,1/19/2018
100085,NaN,24411362869,unconfirmed,Elisia,Manhattan,Harlem,40.80891,-73.94247,United States,US,True,moderate,Entire home/apt,2015.0,$725,$145,2.0,113.0,6/23/2019
100294,NaN,87823753249,verified,Irisha,Queens,Fresh Meadows,40.74271,-73.78749,United States,US,True,moderate,Entire home/apt,2016.0,"$1,043",$209,1.0,18.0,5/2/2019
100312,NaN,36683367732,verified,Emmy,Queens,Flushing,40.76153,-73.80304,United States,US,False,flexible,Private room,2022.0,$208,$42,1.0,69.0,2/27/2019
100354,NaN,33931743606,unconfirmed,Nimrod,Brooklyn,Williamsburg,40.71497,-73.93905,United States,US,True,strict,Entire home/apt,2018.0,"$1,136",$227,7.0,0.0,NaN

In [84]:
# so will drop these 250 rows because the name column is important for our analysis and we cannot impute the missing values in this column because it is a categorical column and it has a lot of unique values. so we will drop these rows.

df.dropna(subset=['Name'], inplace=True)

In [85]:
df.isna().sum()

Name                          0
Host_Id                       0
Host_Identity_Verified      277
Host_Name                   398
Neighbourhood_Group          27
Neighbourhood                16
Lat                           8
Long                          8
Country                     527
Country_Code                123
Instant_Bookable             97
Cancellation_Policy          71
Room_Type                     0
Construction_Year           205
Price                       244
Service_Fee                 273
Minimum_Nights              394
Number_Of_Reviews           182
Last_Review               15796
dtype: int64

In [88]:
df[df['Host_Identity_Verified'].isna()]

,Name,Host_Id,Host_Identity_Verified,Host_Name,Neighbourhood_Group,Neighbourhood,Lat,Long,Country,Country_Code,Instant_Bookable,Cancellation_Policy,Room_Type,Construction_Year,Price,Service_Fee,Minimum_Nights,Number_Of_Reviews,Last_Review
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
6,BlissArtsSpace!,61300605564,NaN,Alberta,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2015.0,$71,$14,45.0,49.0,10/5/2017
19,Hip Historic Brownstone Apartment with Backyard,72145018858,NaN,Martin,Brooklyn,Crown Heights,40.67592,-73.94694,United States,NaN,NaN,moderate,Entire home/apt,2004.0,"$1,095",NaN,3.0,53.0,6/22/2019
23,CBG Helps Haiti Room#2.5,87668933180,NaN,William,Brooklyn,Park Slope,40.67989,-73.97798,United States,NaN,NaN,moderate,Private room,2017.0,"$1,050",$210,1.0,39.0,1/1/2019
25,"MAISON DES SIRENES1,bohemian apartment",48387947293,NaN,Miranda,Brooklyn,Bedford-Stuyvesant,40.68371,-73.94028,United States,NaN,NaN,strict,Entire home/apt,2006.0,"$1,175",$235,2.0,88.0,6/19/2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96336,Ma-Don Hideaway,73975905498,NaN,Lillie & Donald,Brooklyn,Bedford-Stuyvesant,40.69069,-73.92651,United States,US,True,moderate,Entire home/apt,2017.0,"$1,092",$218,2.0,13.0,1/2/2019
96337,Gorgeous room in luxury apartment (2),50042663518,NaN,Jelani,Brooklyn,Clinton Hill,40.68697,-73.96063,United States,US,False,moderate,Private room,2005.0,$536,$107,3.0,10.0,6/5/2019
96338,The Yorkville Gem,16811944489,NaN,Janine,Manhattan,Upper East Side,40.78023,-73.95069,United States,US,False,flexible,Shared room,2003.0,$320,$64,7.0,15.0,7/1/2019
96339,1940's Historic Brooklyn Townhome,73143337197,NaN,Mark,Brooklyn,East Flatbush,40.63863,-73.93826,United States,US,False,moderate,Entire home/apt,2012.0,$597,$119,5.0,2.0,6/19/2019
96340,"Sunny, CENTRAL Williamsburg Room with Rooftop",6659859418,NaN,Samantha,Brooklyn,Williamsburg,40.71446,-73.95992,United States,US,False,flexible,Private room,2015.0,$297,$59,1.0,4.0,8/13/2018

In [89]:
# we will drop these rows as well because the host identity verified column is also important for our analysis and we cannot impute the missing values in this column because it is a categorical column and it has only two unique values which are true and false. so we will drop these rows.
df.dropna(subset=['Host_Identity_Verified'], inplace=True)

In [90]:
df.shape

(101531, 19)

In [91]:
df.isna().sum()

Name                          0
Host_Id                       0
Host_Identity_Verified        0
Host_Name                   397
Neighbourhood_Group          20
Neighbourhood                16
Lat                           8
Long                          8
Country                     527
Country_Code                119
Instant_Bookable             93
Cancellation_Policy          71
Room_Type                     0
Construction_Year           193
Price                       240
Service_Fee                 272
Minimum_Nights              385
Number_Of_Reviews           182
Last_Review               15756
dtype: int64

In [94]:
df.head()

,Name,Host_Id,Host_Identity_Verified,Host_Name,Neighbourhood_Group,Neighbourhood,Lat,Long,Country,Country_Code,Instant_Bookable,Cancellation_Policy,Room_Type,Construction_Year,Price,Service_Fee,Minimum_Nights,Number_Of_Reviews,Last_Review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0,6/22/2019
7,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0,10/5/2017

In [104]:
# I want to fill the missing host name with the value of host id because it is a unique identifier for each host and it will not affect our analysis as much as filling it with a common value like "unknown" or "missing". so we will fill the missing values in the host name column with the corresponding values in the host id column.

df.groupby('Host_Id')['Host_Name'].nunique() > 1

Host_Id
123600518      False
124039648      False
124472619      False
129756565      False
130349612      False
               ...
98758136270    False
98760968631    False
98762661810    False
98762683230    False
98763129024    False
Name: Host_Name, Length: 101531, dtype: bool

In [97]:
df['Host_Name'] = df.groupby('Host_Id')['Host_Name'].transform(lambda x: x.fillna(method='ffill').fillna(method='bfill'))

In [98]:
df['Host_Name'].isna().sum()

np.int64(397)

In [99]:
df.head(10)

,Name,Host_Id,Host_Identity_Verified,Host_Name,Neighbourhood_Group,Neighbourhood,Lat,Long,Country,Country_Code,Instant_Bookable,Cancellation_Policy,Room_Type,Construction_Year,Price,Service_Fee,Minimum_Nights,Number_Of_Reviews,Last_Review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0,6/22/2019
7,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0,10/5/2017
8,Large Furnished Room Near B'way,79384379533,verified,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,US,True,strict,Private room,2005.0,"$1,018",$204,2.0,430.0,6/24/2019
9,Cozy Clean Guest Room - Family Apt,75527839483,unconfirmed,Carl,Manhattan,Upper West Side,40.80178,-73.96723,United States,US,False,strict,Private room,2015.0,$291,$58,2.0,118.0,7/21/2017
10,Cute & Cozy Lower East Side 1 bdrm,1280143094,verified,Miranda,Manhattan,Chinatown,40.71344,-73.99037,United States,US,False,flexible,Entire home/apt,2004.0,$319,$64,1.0,160.0,6/9/2019
11,Beautiful 1br on Upper West Side,18824631834,verified,Alan,Manhattan,Upper West Side,40.80316,-73.96545,United States,US,True,flexible,Entire home/apt,2008.0,$606,$121,5.0,53.0,6/22/2019
12,Central Manhattan/near Broadway,88136055909,verified,NaN,Manhattan,Hell's Kitchen,40.76076,-73.98867,United States,US,False,strict,Private room,2008.0,$714,$143,2.0,188.0,6/23/2019